channels:
- anaconda
- default
dependencies:
- python=3.8
- conda:
  - numpy
- pip:
  - matplotlib
  - pandas
  - argparse
  - recordlinkage
  - scikit-learn
  - streamlit
  - altair
  - metaphone
  - uuid
